# Generated by Django 4.2.8 on 2024-01-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='book_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
